### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by emilstahl** [gillstrom/postnord#1]
```
⋊> ~ postnord -a [apikey] -l da [shipment id]

    [shipment id]  - ENROUTE
      Estimated delivery: 200-01-01 00:00

    undefined
      Signed by: undefined


    2016-10-28 21:05 - Brøndby Pakkecenter - BRC
      Forsendelsen behandles på vores sorteringscenter

    Weight:     11.5 kg
    Length:     0.48 m
    Height:     0.26 m
    Width:      0.32 m
TypeError: Cannot read property 'name' of undefined
    at print (/Users/emil/.nvm/versions/node/v6.7.0/lib/node_modules/postnord/cli.js:82:38)
    at res.TrackingInformationResponse.shipments.forEach.x (/Users/emil/.nvm/versions/node/v6.7.0/lib/node_modules/postnord/cli.js:105:57)
    at Array.forEach (native)
    at fn.then.res (/Users/emil/.nvm/versions/node/v6.7.0/lib/node_modules/postnord/cli.js:105:44)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by gillstrom** [comment]
It seems like all ID's gives different data. Probably just need a check if the object exists.
